"""telegram update dedup

Revision ID: b8febb3480a1
Revises: b2a1c894373b
Create Date: 2026-09-23 14:01:44.276568
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b8febb3480a1"
down_revision: str | None = "b2a1c894373b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telegram_updates",
        sa.Column("update_id", sa.Integer(), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("update_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("telegram_updates")
    # ### end Alembic commands ###
