"""application notified_at

Revision ID: 36beb6fd4f41
Revises: b8febb3480a1
Create Date: 2026-09-23 14:02:49.973457
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "36beb6fd4f41"
down_revision: str | None = "b8febb3480a1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.add_column(sa.Column("notified_at", sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.drop_column("notified_at")

    # ### end Alembic commands ###
